spring:
  application:
    name: CodeJourney-CoLab-Backend
  datasource:
    url: jdbc:mysql://115.29.227.47:3306/cocopals
    # *改成你自己的本地数据库用户名和密码！
    username: root
    password: SQLPASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: codejourneycolab#secret*key-wohenshenmiwohenshenmi
  expiration: 604800000

server:
  port: 8048

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tongji.codejourneycolab.codejourneycolabbackend.entity

sharedb:
 url: http://127.0.0.1:4242/share/opendocument
#
#redis:
#  host: localhost
#  port: 6379
